# ==========================================================================
# AEGIS Protocol - Yield Scanner Workflow
# Trigger: Cron (every 5 minutes)
# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "aegis-yield-scanner-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "aegis-yield-scanner-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
