# ==========================================================================
# AEGIS Protocol - Risk Sentinel Workflow
# Trigger: Log (on-chain event driven)
# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "aegis-risk-sentinel-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "aegis-risk-sentinel-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
